hepsi: derle calistir

derle:
	gcc -I ./include/ -o ./lib/Zaman.o -c ./src/Zaman.c
	gcc -I ./include/ -o ./lib/Gezegen.o -c ./src/Gezegen.c
	gcc -I ./include/ -o ./lib/Kayac.o -c ./src/Kayac.c
	gcc -I ./include/ -o ./lib/BuzDevi.o -c ./src/BuzDevi.c
	gcc -I ./include/ -o ./lib/GazDevi.o -c ./src/GazDevi.c
	gcc -I ./include/ -o ./lib/Cuce.o -c ./src/Cuce.c	
	gcc -I ./include/ -o ./lib/Arac.o -c ./src/Arac.c	
	gcc -I ./include/ -o ./lib/Kisi.o -c ./src/Kisi.c
	gcc -I ./include/ -o ./lib/Dugum.o -c ./src/Dugum.c
	gcc -I ./include/ -o ./lib/Liste.o -c ./src/Liste.c
	gcc -I ./include/ -o ./lib/DosyaOkuma.o -c ./src/DosyaOkuma.c	
	gcc -I ./include/ -o ./lib/Simulasyon.o -c ./src/Simulasyon.c
	gcc -I ./include/ -o ./lib/Test.o -c ./src/Test.c
	gcc -I ./include/ -o ./bin/Test ./lib/Zaman.o ./lib/Gezegen.o ./lib/Kayac.o ./lib/BuzDevi.o ./lib/GazDevi.o ./lib/Cuce.o ./lib/Arac.o ./lib/Kisi.o ./lib/Dugum.o ./lib/Liste.o ./lib/DosyaOkuma.o ./lib/Simulasyon.o ./lib/Test.o

calistir:
	./bin/Test
