Tum: derle calistir


derle:
	g++ -I ./include/ -o ./lib/Gen.o -c ./src/Gen.cpp
	g++ -I ./include/ -o ./lib/GenListe.o -c ./src/GenListe.cpp
	g++ -I ./include/ -o ./lib/Kromozom.o -c ./src/Kromozom.cpp
	g++ -I ./include/ -o ./lib/KromozomListe.o -c ./src/KromozomListe.cpp
	g++ -I ./include/ -o ./lib/Hucre.o -c ./src/Hucre.cpp
	g++ -I ./include/ -o ./lib/Menu.o -c ./src/Menu.cpp
	g++ -I ./include/ -o ./bin/Test ./lib/Gen.o ./lib/GenListe.o ./lib/Kromozom.o ./lib/KromozomListe.o ./lib/Hucre.o ./lib/Menu.o ./src/Main.cpp

calistir:
	./bin/Test